version: '3'
services:
  app:
    build:
      context: ./sklep
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./sklep:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: sklep
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./sklep.sql:/docker-entrypoint-initdb.d/sklep.sql
